# Generated by Django 5.0.6 on 2024-06-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='film',
            table='films',
        ),
    ]
