# Generated by Django 5.0.6 on 2024-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='arena',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='link',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='network',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='season',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='studio',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=512),
        ),
    ]
