# Generated by Django 5.0.6 on 2024-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0002_alter_film_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='arena',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='modified_at',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='season',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='studio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
