# Generated by Django 5.0.6 on 2024-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0004_alter_film_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='need_scrape',
            field=models.BooleanField(default=True),
        ),
    ]
