# Generated by Django 5.0.6 on 2024-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_files/'),
        ),
    ]
