# Generated by Django 5.0.6 on 2024-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_pdf', '0002_alter_pdf_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
