# Generated by Django 5.0.6 on 2024-06-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_film', '0004_alter_film_modified_at'),
        ('core_pdf', '0003_pdf_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='films',
            field=models.ManyToManyField(to='core_film.film'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdf_files/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
