# Generated by Django 5.0.6 on 2024-07-18 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('territory', models.CharField(default='', max_length=255)),
                ('schedule', models.CharField(default='', max_length=255)),
                ('need_scrape', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
